name: Release Production
on:
  push:
    branches:
      - main
  release:
    types: [published]
permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  build-deploy:
    name: Build & Deploy Application
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./react
    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/linkifybio-oidc-role
          role-session-name: linkifybio-role-session
          aws-region: us-east-1
          mask-aws-account-id: 'false'

      - name: Check out code
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Deploy Application
        run: aws s3 sync --delete ./build s3://linkifybio.com/

    